const personsInfo = [
  {
    firstname: 'firstname',
    lastname: 'lastname',
    photo: 'link',
    description: 'persons description',
    githubLink: 'githubLink',
    codewarsLink: 'codewarsLink',
    googleLink: 'googleLink',
  },
  {
    firstname: 'firstname',
    lastname: 'lastname',
    photo: 'link',
    description: 'persons description',
    githubLink: 'githubLink',
    codewarsLink: 'codewarsLink',
    googleLink: 'googleLink',
  },
  {
    firstname: 'firstname',
    lastname: 'lastname',
    photo: 'link',
    description: 'persons description',
    githubLink: 'githubLink',
    codewarsLink: 'codewarsLink',
    googleLink: 'googleLink',
  },
  {
    firstname: 'firstname',
    lastname: 'lastname',
    photo: 'link',
    description: 'persons description',
    githubLink: 'githubLink',
    codewarsLink: 'codewarsLink',
    googleLink: 'googleLink',
  },
  {
    firstname: 'firstname',
    lastname: 'lastname',
    photo: 'link',
    description: 'persons description',
    githubLink: 'githubLink',
    codewarsLink: 'codewarsLink',
    googleLink: 'googleLink',
  },
  {
    firstname: 'firstname',
    lastname: 'lastname',
    photo: 'link',
    description: 'persons description',
    githubLink: 'githubLink',
    codewarsLink: 'codewarsLink',
    googleLink: 'googleLink',
  },
];

export default personsInfo;
